"""initial_schema

Revision ID: 7078760f703a
Revises: 
Create Date: 2026-07-22 08:02:47.573395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7078760f703a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('primary_intent', sa.String(), nullable=False),
    sa.Column('secondary_intents', sa.Text(), nullable=False),
    sa.Column('pain_points_json', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('follow_up_needed', sa.Boolean(), nullable=False),
    sa.Column('follow_up_reason', sa.String(), nullable=True),
    sa.Column('lead_quality', sa.String(), nullable=False),
    sa.Column('customer_sentiment', sa.String(), nullable=False),
    sa.Column('staff_coaching_notes_json', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_analyses_call_id'), 'call_analyses', ['call_id'], unique=False)
    op.create_table('call_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('call_date', sa.Date(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('source_path', sa.String(), nullable=True),
    sa.Column('low_quality', sa.Boolean(), nullable=False),
    sa.Column('quality_note', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_records_call_id'), 'call_records', ['call_id'], unique=True)
    op.create_table('weekly_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('report_markdown', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_call_records_call_id'), table_name='call_records')
    op.drop_table('call_records')
    op.drop_index(op.f('ix_call_analyses_call_id'), table_name='call_analyses')
    op.drop_table('call_analyses')
    # ### end Alembic commands ###
