#!/usr/bin/env python3
"""Compare per-call analyses to human ground truth labels."""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
GROUND_TRUTH_PATH = ROOT / "data" / "ground_truth.yaml"
ANALYSES_DIR = ROOT / "outputs" / "analyses"
REPORT_PATH = ROOT / "docs" / "validation_results.md"


def load_ground_truth() -> dict[str, dict[str, str]]:
    data = yaml.safe_load(GROUND_TRUTH_PATH.read_text(encoding="utf-8"))
    calls = data.get("calls", {})
    return {
        call_id: {
            "primary_intent": row["primary_intent"],
            "outcome": row["outcome"],
        }
        for call_id, row in calls.items()
    }


def load_predictions() -> dict[str, dict[str, str]]:
    predictions: dict[str, dict[str, str]] = {}
    for path in sorted(ANALYSES_DIR.glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        call_id = payload["call"]["call_id"]
        analysis = payload["analysis"]
        predictions[call_id] = {
            "primary_intent": analysis["primary_intent"],
            "outcome": analysis["outcome"],
        }
    return predictions


def accuracy_report(
    truth: dict[str, dict[str, str]], pred: dict[str, dict[str, str]]
) -> tuple[list[str], dict[str, float]]:
    lines: list[str] = []
    call_ids = sorted(truth.keys())
    missing = [cid for cid in call_ids if cid not in pred]
    evaluated = [cid for cid in call_ids if cid in pred]

    intent_correct = sum(
        1 for cid in evaluated if pred[cid]["primary_intent"] == truth[cid]["primary_intent"]
    )
    outcome_correct = sum(
        1 for cid in evaluated if pred[cid]["outcome"] == truth[cid]["outcome"]
    )
    both_correct = sum(
        1
        for cid in evaluated
        if pred[cid]["primary_intent"] == truth[cid]["primary_intent"]
        and pred[cid]["outcome"] == truth[cid]["outcome"]
    )

    n = len(evaluated) or 1
    metrics = {
        "calls_evaluated": float(len(evaluated)),
        "primary_intent_accuracy": intent_correct / n,
        "outcome_accuracy": outcome_correct / n,
        "both_accuracy": both_correct / n,
    }

    lines.append(f"Calls in ground truth: {len(call_ids)}")
    lines.append(f"Calls with analysis JSON: {len(evaluated)}")
    if missing:
        lines.append(f"Missing analyses: {', '.join(missing)}")
    lines.append("")
    lines.append(
        f"Primary intent accuracy: {intent_correct}/{len(evaluated)} ({metrics['primary_intent_accuracy']:.0%})"
    )
    lines.append(
        f"Outcome accuracy: {outcome_correct}/{len(evaluated)} ({metrics['outcome_accuracy']:.0%})"
    )
    lines.append(
        f"Both correct: {both_correct}/{len(evaluated)} ({metrics['both_accuracy']:.0%})"
    )
    lines.append("")
    lines.append("Per-call comparison:")
    lines.append("")
    lines.append("| Call | Intent (expected -> actual) | Outcome (expected -> actual) | Match |")
    lines.append("|------|---------------------------|------------------------------|-------|")

    for cid in call_ids:
        if cid not in pred:
            lines.append(f"| {cid} | — | — | missing analysis |")
            continue
        te, ta = truth[cid]["primary_intent"], pred[cid]["primary_intent"]
        oe, oa = truth[cid]["outcome"], pred[cid]["outcome"]
        ok = te == ta and oe == oa
        lines.append(
            f"| {cid} | {te} -> {ta} | {oe} -> {oa} | {'PASS' if ok else 'FAIL'} |"
        )

    return lines, metrics


def write_markdown(lines: list[str], metrics: dict[str, float]) -> None:
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body = "\n".join(lines)
    md = f"""# CallGist validation results

Generated by `scripts/ground_truth_review.py` on {stamp}.

## Summary

- Calls evaluated: **{int(metrics['calls_evaluated'])}**
- Primary intent accuracy: **{metrics['primary_intent_accuracy']:.0%}**
- Outcome accuracy: **{metrics['outcome_accuracy']:.0%}**
- Both fields correct: **{metrics['both_accuracy']:.0%}**

Ground truth: [`data/ground_truth.yaml`](../data/ground_truth.yaml)  
Analyses: [`outputs/analyses/`](../outputs/analyses/)

## Detail

{body}
"""
    REPORT_PATH.write_text(md, encoding="utf-8")


def main() -> None:
    if not GROUND_TRUTH_PATH.is_file():
        print(f"Ground truth not found: {GROUND_TRUTH_PATH}")
        sys.exit(1)

    truth = load_ground_truth()
    pred = load_predictions()
    lines, metrics = accuracy_report(truth, pred)

    for line in lines:
        print(line)

    write_markdown(lines, metrics)
    print(f"\nWrote {REPORT_PATH}")


if __name__ == "__main__":
    main()


